
pypi:
  image: python:3.6-alpine
  stage: deploy
  cache: {}
  only:
    - /^\d+\.\d+\.\d+([abc]\d*)?$/
  script:
    - apk add --no-cache gcc musl-dev libffi-dev libressl-dev
    - pip install -U twine
    - python setup.py sdist
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
